var schemainfo = {
		"ext.schema.prefix" : "kospo",
		"kospo.schema.root" : "MaterialInfo",
		"kospo.schema.arrayroot" : "MaterialArrayInfo",
		"kospo.schema.ns" : "http://www.kospo.go.kr",
		"kospo.schema.displayname.Material" : "자재",
	    "kospo.schema.displayname.Materials" : "자재",
		"kospo.schema.displayname.MaterialCode" : "자재코드",
		"kospo.schema.display.MaterialCode" : "hidden",
		"kospo.schema.readonly.MaterialCode" : "readonly",
		"kospo.schema.displayname.Name" : "자재명",
		"kospo.schema.display.Name" : "text",
		"kospo.schema.readonly.Name" : "readonly",
		"kospo.schema.displayname.Category" : "자재분류",
		"kospo.schema.display.Category" : "text",
		"kospo.schema.readonly.Category" : "readonly",
		"kospo.schema.displayname.AvgUnitPrice" : "평균단가시세",
		"kospo.schema.display.AvgUnitPrice" : "text",
		"kospo.schema.readonly.AvgUnitPrice" : "readonly",
		"kospo.schema.displayname.Description" : "설명",
		"kospo.schema.display.Description" : "text",
		"kospo.schema.readonly.Description" : "readonly",
		"kospo.schema.displayname.Stocks" : "재고현황",
		"kospo.schema.displayname.Stock" : "재고현황",
		"kospo.schema.displayname.StockAmount" : "재고수량",
		"kospo.schema.display.StockAmount" : "text",
		"kospo.schema.readonly.StockAmount" : "readonly",
		"kospo.schema.displayname.KeepAmount" : "적정유지 수량",
		"kospo.schema.display.KeepAmount" : "text",
		"kospo.schema.readonly.KeepAmount" : "readonly",
		"kospo.schema.displayname.Location" : "창고 위치",
		"kospo.schema.display.Location" : "text",
		"kospo.schema.readonly.Location" : "readonly",
		"kospo.schema.displayname.MaterialDelivery" : "인도현황",
		"kospo.schema.display.MaterialDelivery" : "text",
		"kospo.schema.readonly.MaterialDelivery" : "readonly",
		"kospo.schema.displayname.ReqID" : "요청자",
		"kospo.schema.display.ReqID" : "text",
		"kospo.schema.readonly.ReqID" : "readonly",
		"kospo.schema.displayname.Request" : "요청내역",
		"kospo.schema.display.Request" : "text",
		"kospo.schema.readonly.Request" : "readonly",
		"kospo.schema.displayname.Requestor" : "자재 요청자",
		"kospo.schema.display.Requestor" : "text",
		"kospo.schema.readonly.Requestor" : "readonly",
		"kospo.schema.displayname.ReqAmount" : "요청 수량",
		"kospo.schema.display.ReqAmount" : "text",
		"kospo.schema.readonly.ReqAmount" : "",
		"kospo.schema.displayname.ReqDT" : "요청 일시",
		"kospo.schema.display.ReqDT" : "text",
		"kospo.schema.readonly.ReqDT" : "readonly",
		"kospo.schema.displayname.ReqComment" : "특기사항",
		"kospo.schema.display.ReqComment" : "text",
		"kospo.schema.readonly.ReqComment" : "",
		"kospo.schema.displayname.DeliveryDate" : "인도 일시",
		"kospo.schema.display.DeliveryDate" : "text",
		"kospo.schema.readonly.DeliveryDate" : "readonly",
		"kospo.schema.displayname.Supplier" : "공급사",
		"kospo.schema.display.Supplier" : "text",
		"kospo.schema.readonly.Supplier" : "readonly",
		"kospo.schema.displayname.SupplierDetermine" : "공급사 평가결과",
		"kospo.schema.display.SupplierDetermine" : "text",
		"kospo.schema.readonly.SupplierDetermine" : "readonly",
		"kospo.schema.displayname.Suppliers" : "공급사현황",
		"kospo.schema.display.Suppliers" : "text",
		"kospo.schema.readonly.Suppliers" : "readonly",
		"kospo.schema.displayname.SupplierCode" : "공급사 코드",
		"kospo.schema.display.SupplierCode" : "hidden",
		"kospo.schema.readonly.SupplierCode" : "readonly",
		"kospo.schema.displayname.SupplierName" : "회사명",
		"kospo.schema.display.SupplierName" : "text",
		"kospo.schema.readonly.SupplierName" : "readonly",
		"kospo.schema.displayname.ContractSupplier" : "계약 업체",
		"kospo.schema.display.ContactSupplier" : "text",
		"kospo.schema.readonly.ContractSupplier" : "readonly",
		"kospo.schema.displayname.CEOName" : "대표이사 이름",
		"kospo.schema.display.CEOName" : "text",
		"kospo.schema.readonly.CEOName" : "readonly",
		"kospo.schema.displayname.CEOSSN" : "대표이사 주민번호",
		"kospo.schema.display.CEOSSN" : "hidden",
		"kospo.schema.readonly.CEOSSN" : "readonly",
		"kospo.schema.displayname.NumEmployee" : "임직원 수",
		"kospo.schema.display.NumEmployee" : "text",
		"kospo.schema.readonly.NumEmployee" : "readonly",
		"kospo.schema.displayname.OneYearResult" : "실적1년전 금액",
		"kospo.schema.display.OneYearResult" : "hidden",
		"kospo.schema.readonly.OneYearResult" : "readonly",
		"kospo.schema.displayname.TwoYearResult" : "실적2년전 금액",
		"kospo.schema.display.TwoYearResult" : "hidden",
		"kospo.schema.readonly.TwoYearResult" : "readonly",
		"kospo.schema.displayname.ThreeYearResult" : "실적3년전 금액",
		"kospo.schema.display.ThreeYearResult" : "hidden",
		"kospo.schema.readonly.ThreeYearResult" : "readonly",
		"kospo.schema.displayname.MasterHeadCnt" : "기술사 또는 기능장 보유 인원수",
		"kospo.schema.display.MasterHeadCnt" : "hidden",
		"kospo.schema.readonly.MasterHeadCnt" : "readonly",
		"kospo.schema.displayname.TechicianHeadCnt" : "기사 또는 산업기사 보유 인원수",
		"kospo.schema.display.TechicianHeadCnt" : "hidden",
		"kospo.schema.readonly.TechicianHeadCnt" : "readonly",
		"kospo.schema.displayname.EngineerHeadCnt" : "기능사 보유 인원수",
		"kospo.schema.display.EngineerHeadCnt" : "hidden",
		"kospo.schema.readonly.EngineerHeadCnt" : "readonly",
		"kospo.schema.displayname.CorpSize" : "기업규모",
		"kospo.schema.display.CorpSize" : "text",
		"kospo.schema.readonly.CorpSize" : "readonly",
		"kospo.schema.displayname.BondGrade" : "회사채에 대한 신용평가 등급",
		"kospo.schema.display.BondGrade" : "hidden",
		"kospo.schema.readonly.BondGrade" : "readonly",
		"kospo.schema.displayname.BillGrade" : "기업어음에 대한 신용평가 등급",
		"kospo.schema.display.BillGrade" : "hidden",
		"kospo.schema.readonly.BillGrade" : "readonly",
		"kospo.schema.displayname.FactoryYears" : "공장등록 연수",
		"kospo.schema.display.FactoryYears" : "hidden",
		"kospo.schema.readonly.FactoryYears" : "readonly",
		"kospo.schema.displayname.MaterialBySupplier" : "공급사별 공급 자재 목록",
		"kospo.schema.display.MaterialBySupplier" : "text",
		"kospo.schema.readonly.MaterialBySupplier" : "readonly",
		"kospo.schema.displayname.AvgInventoryAmt" : "평균보유재고수량",
		"kospo.schema.display.AvgInventoryAmt" : "hidden",
		"kospo.schema.readonly.AvgInventoryAmt" : "readonly",
		"kospo.schema.displayname.BidNotice" : "입찰공고",
		"kospo.schema.display.BidNotice" : "text",
		"kospo.schema.readonly.BidNotice" : "readonly",
		"kospo.schema.displayname.BidAmount" : "자재 코드",
		"kospo.schema.display.BidAmount" : "text",
		"kospo.schema.readonly.BidAmount" : "readonly",
		"kospo.schema.displayname.ExpectUnitPrice" : "예상 단가",
		"kospo.schema.display.ExpectUnitPrice" : "text",
		"kospo.schema.readonly.ExpectUnitPrice" : "readonly",
		"kospo.schema.displayname.CompleteDate" : "완료일시",
		"kospo.schema.display.CompleteDate" : "text",
		"kospo.schema.readonly.CompleteDate" : "readonly",
		"kospo.schema.displayname.MaterialSupply" : "공급현황",
		"kospo.schema.display.MaterialSupply" : "text",
		"kospo.schema.readonly.MaterialSupply" : "readonly",
		"kospo.schema.displayname.SupplierSCMStatus" : "공급사 SCM 상태",
		"kospo.schema.display.SupplierSCMStatus" : "text",
		"kospo.schema.readonly.SupplierSCMStatus" : "readonly",
		"kospo.schema.displayname.SupplierSCMStatus" : "공급사 SCM 상태",
		"kospo.schema.display.SupplierSCMStatus" : "text",
		"kospo.schema.readonly.SupplierSCMStatus" : "readonly",
		"kospo.schema.displayname.Result" : "결과",
		"kospo.schema.display.Result" : "text",
		"kospo.schema.readonly.Result" : "readonly",
		"kospo.schema.displayname.BaseScore" : "기본점수",
		"kospo.schema.display.BaseScore" : "text",
		"kospo.schema.readonly.BaseScore" : "readonly",
		"kospo.schema.displayname.AddScore" : "가산점",
		"kospo.schema.display.AddScore" : "text",
		"kospo.schema.readonly.AddScore" : "readonly",
		"kospo.schema.displayname.TotalScore" : "총점",
		"kospo.schema.display.TotalScore" : "text",
		"kospo.schema.readonly.TotalScore" : "readonly",
		"kospo.schema.displayname.ResultReason" : "사유",
		"kospo.schema.display.ResultReason" : "hidden",
		"kospo.schema.readonly.ResultReason" : "readonly"
	}

var prefix = schemainfo['ext.schema.prefix'];
var root = schemainfo[prefix+'.schema.root'];
var arrayroot = schemainfo[prefix+'.schema.arrayroot'];
var ns = schemainfo[prefix+'.schema.ns'];